"""Tests for dlh_airflow_common __init__ module."""

from unittest.mock import patch

import pytest

from dlh_airflow_common import __version__, get_dag_description


class TestGetDagDescription:
    """Test suite for get_dag_description function."""

    def test_get_dag_description_without_custom_description(self) -> None:
        """Test get_dag_description returns version info when no description provided."""
        result = get_dag_description()

        assert f"Generated by dlh-airflow-common v{__version__}" == result

    def test_get_dag_description_with_custom_description(self) -> None:
        """Test get_dag_description includes custom description."""
        custom_desc = "Daily data pipeline"
        result = get_dag_description(custom_desc)

        assert custom_desc in result
        assert f"dlh-airflow-common v{__version__}" in result
        assert result == f"{custom_desc} | Generated by dlh-airflow-common v{__version__}"

    def test_get_dag_description_with_empty_string(self) -> None:
        """Test get_dag_description with empty string returns only version info."""
        result = get_dag_description("")

        assert result == f"Generated by dlh-airflow-common v{__version__}"

    def test_get_dag_description_with_none(self) -> None:
        """Test get_dag_description with None returns only version info."""
        result = get_dag_description(None)

        assert result == f"Generated by dlh-airflow-common v{__version__}"

    @patch("dlh_airflow_common.__version__", "1.2.3")
    def test_get_dag_description_uses_current_version(self) -> None:
        """Test that get_dag_description uses the actual version."""
        # Re-import to get the patched version in the function
        from dlh_airflow_common import get_dag_description as get_desc

        result = get_desc("My DAG")

        assert "v1.2.3" in result


class TestModuleExports:
    """Test suite for module exports."""

    def test_version_is_exported(self) -> None:
        """Test that __version__ is exported."""
        from dlh_airflow_common import __version__

        assert __version__ is not None
        assert isinstance(__version__, str)

    def test_get_dag_description_is_exported(self) -> None:
        """Test that get_dag_description is exported."""
        from dlh_airflow_common import get_dag_description

        assert callable(get_dag_description)

    def test_all_exports(self) -> None:
        """Test that __all__ contains expected exports."""
        import dlh_airflow_common

        assert "BaseOperator" in dlh_airflow_common.__all__
        assert "DbtOperator" in dlh_airflow_common.__all__
        assert "__version__" in dlh_airflow_common.__all__
        assert "get_dag_description" in dlh_airflow_common.__all__
