"""DLH Airflow Common Library.

This library provides common Airflow operators and utilities for data pipelines.
"""

from typing import Optional

try:
    from dlh_airflow_common._version import version as __version__
except ImportError:  # pragma: no cover
    __version__ = "0.0.0.dev0"

from dlh_airflow_common.hooks.dbt import DbtHook, DbtTaskResult
from dlh_airflow_common.operators.base import BaseOperator
from dlh_airflow_common.operators.dbt import DbtOperator
from dlh_airflow_common.validation import (
    ValidationResult,
    YamlDagValidator,
    validate_yaml_directory,
    validate_yaml_file,
)


def get_dag_description(description: str | None = None) -> str:
    """Generate a DAG description that includes the library version.

    Args:
        description: Optional custom description to prepend.

    Returns:
        A description string with the library version appended.

    Example:
        >>> from dlh_airflow_common import get_dag_description
        >>> with DAG(
        ...     dag_id="my_dag",
        ...     description=get_dag_description("Daily data pipeline"),
        ...     ...
        ... ) as dag:
    """
    version_info = f"Generated by dlh-airflow-common v{__version__}"
    if description:
        return f"{description} | {version_info}"
    return version_info


__all__ = [
    "BaseOperator",
    "DbtOperator",
    "DbtHook",
    "DbtTaskResult",
    "ValidationResult",
    "YamlDagValidator",
    "validate_yaml_file",
    "validate_yaml_directory",
    "__version__",
    "get_dag_description",
]
